DROP TABLE IF EXISTS CLASS_SCHEDULE;
DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS ROOM;

CREATE TABLE PROFESSOR (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE SUBJECT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    taught_by BIGINT NOT NULL,
    FOREIGN KEY (taught_by) REFERENCES PROFESSOR(id)
);

CREATE TABLE ROOM (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE CLASS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(255) NOT NULL UNIQUE,
    subject_id BIGINT NOT NULL,
    FOREIGN KEY (subject_id) REFERENCES SUBJECT(id)
);

CREATE TABLE CLASS_SCHEDULE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    class_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    day_of_week VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    FOREIGN KEY (class_id) REFERENCES CLASS(id),
    FOREIGN KEY (room_id) REFERENCES ROOM(id)
);